### ISSUE TITLE
slc start can't deploy to multiapp

### ISSUE THREAD

**Issue by cgole** [strongloop/strong-start#8] opened 2015-04-28 18:09 UTC
slc start
Cannot POST /default

assert.js:326
assert.ifError = function(err) { if (err) {throw err;}};
                                                 ^
Error: HTTP error 404
    at Error (<anonymous>)
    at /usr/local/lib/node_modules/strongloop/node_modules/strong-start/node_modules/strong-deploy/lib/post-json.js:55:16
    at ConcatStream.<anonymous> (/usr/local/lib/node_modules/strongloop/node_modules/strong-start/node_modules/strong-deploy/node_modules/concat-stream/index.js:36:43)
    at ConcatStream.emit (events.js:117:20)
    at finishMaybe (/usr/local/lib/node_modules/strongloop/node_modules/strong-start/node_modules/strong-deploy/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:460:14)
    at afterWrite (/usr/local/lib/node_modules/strongloop/node_modules/strong-start/node_modules/strong-deploy/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:340:3)
    at /usr/local/lib/node_modules/strongloop/node_modules/strong-start/node_modules/strong-deploy/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:327:9
    at process._tickCallback (node.js:448:13)

**Comment by sam-github** [comment] 2015-05-02 00:50
Duplicate of

> having log-dump not have a default SRV_ID is hostile to users, particularly with slc start

from https://github.com/strongloop-internal/scrum-nodeops/issues/495

@chandadharap @cgole you should read through above.

I agree this is a problem, maybe it should be pulled out of 495 and into a bug. Maybe some other issues in there are also of interest.

**Closed** 2015-05-04 16:07 UTC
Labels: bug
